
package com.ficto.parrot.soap.domain;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebSerivceImpl", targetNamespace = "http://service.jws.fictio.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebSerivceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://service.jws.fictio.com/", className = "com.ficto.parrot.soap.domain.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://service.jws.fictio.com/", className = "com.ficto.parrot.soap.domain.SayHiResponse")
    @Action(input = "http://service.jws.fictio.com/WebSerivceImpl/sayHiRequest", output = "http://service.jws.fictio.com/WebSerivceImpl/sayHiResponse")
    public String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
