
package com.ficto.parrot.soap.domain;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebSerivceImplService", targetNamespace = "http://service.jws.fictio.com/", wsdlLocation = "http://127.0.0.1:9888/jws/ws?wsdl")
public class WebSerivceImplService
    extends Service
{

    private final static URL WEBSERIVCEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERIVCEIMPLSERVICE_EXCEPTION;
    private final static QName WEBSERIVCEIMPLSERVICE_QNAME = new QName("http://service.jws.fictio.com/", "WebSerivceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9888/jws/ws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERIVCEIMPLSERVICE_WSDL_LOCATION = url;
        WEBSERIVCEIMPLSERVICE_EXCEPTION = e;
    }

    public WebSerivceImplService() {
        super(__getWsdlLocation(), WEBSERIVCEIMPLSERVICE_QNAME);
    }

    public WebSerivceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERIVCEIMPLSERVICE_QNAME, features);
    }

    public WebSerivceImplService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERIVCEIMPLSERVICE_QNAME);
    }

    public WebSerivceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERIVCEIMPLSERVICE_QNAME, features);
    }

    public WebSerivceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebSerivceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebSerivceImpl
     */
    @WebEndpoint(name = "WebSerivceImplPort")
    public WebSerivceImpl getWebSerivceImplPort() {
        return super.getPort(new QName("http://service.jws.fictio.com/", "WebSerivceImplPort"), WebSerivceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebSerivceImpl
     */
    @WebEndpoint(name = "WebSerivceImplPort")
    public WebSerivceImpl getWebSerivceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.jws.fictio.com/", "WebSerivceImplPort"), WebSerivceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERIVCEIMPLSERVICE_EXCEPTION!= null) {
            throw WEBSERIVCEIMPLSERVICE_EXCEPTION;
        }
        return WEBSERIVCEIMPLSERVICE_WSDL_LOCATION;
    }

}
